# Generated by Django 4.2.30 on 2026-04-12 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(25)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('background_notes', models.TextField(blank=True)),
                ('school_status', models.CharField(choices=[('attending', 'Attending'), ('dropped', 'Dropped Out'), ('completed', 'Completed')], max_length=20)),
                ('family_support_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offence_type', models.CharField(choices=[('theft', 'Theft'), ('vandalism', 'Vandalism'), ('assault', 'Assault'), ('drug_related', 'Drug Related'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious')], max_length=10)),
                ('date_reported', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offences', to='justice_app.youth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
