# Generated by Django 6.0.5 on 2026-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('Community', 'Community'), ('Counselling', 'Counselling'), ('Education', 'Education'), ('Rehabilitation', 'Rehabilitation'), ('Intensive Support', 'Intensive Support'), ('Mentoring', 'Mentoring')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='offence',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='youth',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offence',
            name='severity',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Serious', 'Serious')], max_length=10),
        ),
        migrations.AlterField(
            model_name='youth',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youth',
            name='family_support_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='youth',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='youth',
            name='school_status',
            field=models.CharField(choices=[('Attending', 'Attending'), ('Dropped Out', 'Dropped Out')], max_length=20),
        ),
        migrations.AddField(
            model_name='youth',
            name='support_programs',
            field=models.ManyToManyField(blank=True, to='justice_app.supportprogram'),
        ),
    ]
