# Generated by Django 4.2.30 on 2026-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('counselling', 'Counselling'), ('training', 'Skill Training'), ('community', 'Community Service')], max_length=20)),
                ('target_severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='offence',
            name='offence_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('vandalism', 'Vandalism'), ('assault', 'Assault'), ('drug', 'Drug Related'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offence',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious')], max_length=20),
        ),
        migrations.AlterField(
            model_name='youth',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='youth',
            name='support_programs',
            field=models.ManyToManyField(blank=True, to='justice_app.supportprogram'),
        ),
    ]
