# Generated by Django 4.2.29 on 2026-04-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('counselling', 'Counselling'), ('training', 'Training'), ('community_service', 'Community Service')], max_length=30)),
                ('description', models.TextField()),
                ('minimum_age', models.PositiveIntegerField()),
                ('maximum_age', models.PositiveIntegerField()),
                ('supported_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_reason', models.TextField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='suggested', max_length=20)),
                ('support_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justice_app.supportprogram')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justice_app.youth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
